### ISSUE TITLE
THIS IS AWESOME!

### ISSUE THREAD

**Issue by hamin** [sdegutis/pasteomatic#2]
Sorry this really isn't an issue just wanted to say that this is AWESOME! Totally gonna use this. Also I've been looking for an example of a spotloght/alfred type mac app interface for a while. This is an EXCELLENT reference :). Thank you, and as a I way to thank you send me an email aminharis7ATgmail.com . I'd like to give you a copy of a Mac App I have in the mac app store http://mackernews.com :) Thanks again this is awesome :)

**Comment by sdegutis** [comment]
Haha, well I'm glad you liked it. Thanks for the offer but I don't really have need for any apps. I don't really like being on the computer much.

**Comment by sdegutis** [comment]
@hamin I see that your app is a Mac interface to Hacker News. I really like the way it looks! Very pretty and stylish. I'm not a fan of the HN community though. Way too much start-up culture and naïveté for my stomach.

**Comment by hamin** [comment]
@sdegutis lol that's totally understandable, if you still want a free copy just email me and i'll send a code :). I've been working on another mac app on the side that's kind of a bigger project eventhough its almost done. But i've been wanting to do this one idea i had for a mac app and really wanted a spotlight like interface so I'm super excited about that now :).

**Comment by sdegutis** [comment]
Glad to hear. You might also like my other repo `choose`.

**Comment by hamin** [comment]
hmm interesting...i'm a bit confused byt hat.. same interface but where is the input for the list items coming from?

**Comment by hamin** [comment]
ah got it i see the fakedata.h neat this is a more stripped down version of the interface which is great :)

**Comment by sdegutis** [comment]
@hamin It comes from `stdin`. You can pipe anything to it. Try this: `find . -f | choose`

**Comment by sdegutis** [comment]
@hamin Oops that's incorrect. I mean, try this: `find . -type f | choose`

**Comment by hamin** [comment]
@sdegutis nice :)
